export const LOG_IN = "LOG_IN";
export const LOG_OUT = "LOG_OUT";
export const CREATE_USER = "CREATE_USER";
export const FETCH_USER = "FETCH_USER";
export const UPDATE_USER = "UPDATE_USER";

export const CLEAR_MESSAGES = "CLEAR_MESSAGES";
export const ADD_FLASH_MESSAGE = "ADD_FLASH_MESSAGE";



// Organizations
export const FETCH_ORGANIZATION= "FETCH_ORGANIZATION";
export const DELETE_ORGANIZATION= "DELETE_ORGANIZATION";
export const FETCH_ORGANIZATIONS = "FETCH_ORGANIZATIONS";
export const CREATE_ORGANIZATION= "CREATE_ORGANIZATION";
export const UPDATE_ORGANIZATION= "UPDATE_ORGANIZATION";

// Projects
export const FETCH_PROJECT= "FETCH_PROJECT";
export const DELETE_PROJECT= "DELETE_PROJECT";
export const FETCH_PROJECTS = "FETCH_PROJECTS";
export const CREATE_PROJECT= "CREATE_PROJECT";
export const UPDATE_PROJECT= "UPDATE_PROJECT";


// Sticky Messages

export const FETCH_STICKY_MESSAGE= "FETCH_STICKY_MESSAGE";
export const DELETE_STICKY_MESSAGE= "DELETE_STICKY_MESSAGE";
export const FETCH_STICKY_MESSAGES = "FETCH_STICKY_MESSAGES";
export const CREATE_STICKY_MESSAGE= "CREATE_STICKY_MESSAGE";
export const UPDATE_STICKY_MESSAGE= "UPDATE_STICKY_MESSAGE";


